### PR TITLE
Modify module to more closely follow puppetlabs standards

### PR DESCRIPTION
**Pull request by brdude**

### CODE REVIEW

**Comment by brdude** [comment]
Any word on this? Is there anything I can do to help this move along? Any changes you find necessary?

**Comment by ethanculler** [comment]
Hey Rodrigo,

Sorry about the slow turn around. We have been reviewing and testing this, and will have any improvements (and/or an approval) for you soon.

Thanks again for your work on this.

**Comment by samjdacanay** [comment]
Hi Rodrigo,

Thanks for your very thorough update to this module! The changes look great, and it's awesome to have additional eyes keeping this up to date with Puppet's best practices. After an in depth review, there are a few places where this could be made to better fit LogicMonitor's architecture (for more information, see documentation here: http://help.logicmonitor.com/home/architecture/). Functionally speaking everything works great, these changes are simply to keep the usage of this module consistent for our non-puppet use cases.

We noticed that you made the logicmonitor class synonymous with the collector class (which now consists of the installer and the service classes) Since the ::logicmonitor::master class inherits from this class, it forces a collector install on any node with the ::logicmonitor::master class. To ensure consistency with our customers' use cases outside of puppet, and for increased flexibility for our module users, we would prefer to not force a collector install based on the ::logicmonitor::master class.

Next, we noticed that the ::logicmonitor::host and ::logicmonitor::hostgroup no longer inherit from ::logicmonitor (which was how they previously retrieved the credentials for the logicmonitor account). This means that for each specification of these classes, the user has to pass in the account credentials, instead of just in the config.pp (which is now params.pp). There needs to be a way for these classes to retrieve credentials from params or ::logicmonitor, as long as doing so doesn't force the installation of the logicmonitor collector.

We have some questions about the additional dependencies introduced in this iteration. It appears that puppetlabs/stdlib is only needed for the "validate_<object>" functions used in some classes. Is there a reason that you are using these validate functions rather than adding additional parameter validation at the resource type level? It would appear that the same functionality without the new dependency could be achieved by modifying the type definitions (e.g. lib/puppet/type/lm_hostgroup.rb).

Thanks!

**Comment by brdude** [comment]
Sorry for the delay in getting back to this but I could not spare the time earlier.

::logicmonitor::master inheriting from ::logicmonitor was a mistake that has now been fixed and one should no longer be reliant on the other.

::logicmonitor::host and ::logicmonitor::hostgroup should now only inherit the appropriate parameters from ::logicmonitor which in turn inherits them from params.pp. This lets a user also edit params.pp to add their user creds if they so whish to do. But I would have to advise against this last case as this would make the creds available to anyone that has access to the "edited" version of the module. This is the exact case scenario that puppetlabs created hiera to be used for.

I'm using the puppetlabs/stdlib as it is a very widely used module which was created for this particular use and has been used in a variety of community available puppet modules. You are right that the functionality could be replicated but I'd rather not duplicate the effort that the folks at puppetlabs have put forward for this. If anything I'd rather just remove it from the module and let the user validate it them selves.

**Comment by ethanculler** [comment]
Rodrigo,

That last point regarding hiera makes perfect sense. We weren't thinking
about it that way. Especially since parameterized classes will
automatically look up values from hiera. (to be completely fair this module
was developed prior to the release of Hiera and has been rather slow to
evolve)

I will take a look at your newest version soon (hopefully in the next
couple of days, however I know how it is to have little time to spare) and
look forward to getting your changes merged in.

Thanks again for taking the time to make these updates.

~Ethan

Ethan Culler-Mayeno
ecullermayeno@gmail.com
(510) 847-5321

**Comment by ethanculler** [comment]
Hey Rodrigo,

I've been reading through and testing your pull request. So far it looks excellent except for one slight design change. I've spoken to the product team and they have confirmed that we would like to make sure that the inclusion of a collector is explicit rather than implicit as part of including the top level LogicMonitor class. Assuming that the rest of my testing goes well, I'm happy to merge this in and perform that small organization change myself after the merge.

Thanks again for putting so much time into this project!

~Ethan

**Comment by ethanculler** [comment]
Hey Rodrigo,

After the final round of testing, we would like to merge your changes to get them into the code. However since there are a couple of small design changes to make, we were hoping to merge into the develop branch. I'm going to close this pull request, but if you can re-submit this pull request to the develop branch, I will merge your changes in and publish to master after some small changes.

Let me know if that works for you, and thanks again!

**Comment by brdude** [comment]
New PR to DEV branch created.

**Pull request closed without merging**
